apiVersion: v1
kind: Service
metadata:
  name: registry-service
  namespace: devops-tools
spec:
  selector:
    app: docker-registry
  ports:
    - port: 5000
      targetPort: 5000
  type: LoadBalancer