apiVersion: v1
kind: PersistentVolume
metadata:
  name: registry-pv-volume
  labels:
    type: nfs
spec:
  storageClassName: nfs-share
  claimRef:
    name: registry-pv-claim
    namespace: devops-tools
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 192.168.56.1
    path: /mnt/nfs_share/registry
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registry-pv-claim
  namespace: devops-tools
spec:
  storageClassName: nfs-share
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
